Integration test
obiba/mica2-home pull request #70
Opened 2018-02-08 17:07 UTC by smirfolio

Testing visual regression based on BackStopJs tools 
Please see the visual_regression/README.md file

2018-02-08 17:16 UTC, ymarcon requested changes

2018-02-08 17:16 UTC, ymarcon commented on Makefile
> +include visual_regression/Makefile
There is no such folder

2018-02-16 20:51 UTC, kazoompa approved these changes

2018-02-16 20:52 UTC, smirfolio commented on Makefile
> +include visual_regression/Makefile
The folder was added

2018-02-16 21:33 UTC, merged